theme: jekyll-theme-minimal
title: tdalon/ahk
description: A collection of AutoHotkey-based tools and utilities - including the PowerTools suite enhancing Microsoft Office 365 and HCL Connections.
logo: /assets/img/favicon.png
show_downloads: False
google_analytics: UA-179982805-1
navigation:
  - title: Home
    url: /
  - title: PowerTools
    url: PowerTools
  - title: Changelogs
    url: PowerTools-Changelogs
